"""Typed, versioned records that define the corpus (PROJECT.md §6)."""

from edgefit.schema.common import (
    ActivationQuant,
    AttentionVariant,
    Dtype,
    Granularity,
    NormType,
    Outcome,
    PowerSource,
    QuantAlgorithm,
    RuntimeKind,
    StressProfile,
    TaskType,
    ThermalState,
    canonical_json,
    content_hash,
)
from edgefit.schema.config import (
    CONFIG_SCHEMA_VERSION,
    CalibrationConfig,
    ConfigRecord,
    CoreMLComputeUnits,
    ExecutionConfig,
    GraphOptLevel,
    ModelRef,
    OrtProvider,
    OrtRuntimeConfig,
    PartitionConfig,
    QuantizationConfig,
    RuntimeConfig,
)
from edgefit.schema.fingerprint import GraphFingerprint
from edgefit.schema.host import DeviceFingerprint, HostState
from edgefit.schema.measurement import (
    MEASUREMENT_SCHEMA_VERSION,
    MIN_RUNS,
    CalibrationProbe,
    FallbackReport,
    MeasurementRecord,
    Metrics,
    RunStats,
)

__all__ = [
    "CONFIG_SCHEMA_VERSION",
    "MEASUREMENT_SCHEMA_VERSION",
    "MIN_RUNS",
    "ActivationQuant",
    "AttentionVariant",
    "CalibrationConfig",
    "CalibrationProbe",
    "ConfigRecord",
    "CoreMLComputeUnits",
    "DeviceFingerprint",
    "Dtype",
    "ExecutionConfig",
    "FallbackReport",
    "GraphFingerprint",
    "GraphOptLevel",
    "Granularity",
    "HostState",
    "MeasurementRecord",
    "Metrics",
    "ModelRef",
    "NormType",
    "OrtProvider",
    "OrtRuntimeConfig",
    "Outcome",
    "PartitionConfig",
    "PowerSource",
    "QuantAlgorithm",
    "QuantizationConfig",
    "RunStats",
    "RuntimeConfig",
    "RuntimeKind",
    "StressProfile",
    "TaskType",
    "ThermalState",
    "canonical_json",
    "content_hash",
]
